export type Organization = {
	login: string;
	id: number;
	node_id: string;
	url: string;
	repos_url: string;
	events_url: string;
	hooks_url: string;
	issues_url: string;
	members_url: string;
	public_members_url: string;
	avatar_url: string;
	description: string | null;
	name: string;
	blog: string;
	location: string;
	email: string;
	twitter_username: string | null;
	is_verified: boolean;
	has_organization_projects: boolean;
	has_repository_projects: boolean;
	public_repos: number;
	public_gists: number;
	followers: number;
	following: number;
	html_url: string;
	type: string;
	total_private_repos: number;
	owned_private_repos: number;
	private_gists: number | null;
	disk_usage: number | null;
	collaborators: number | null;
	billing_email: string | null;
};
